### ISSUE TITLE
Battery temperature conversion both to ºC and to ºF (one of them is wrong)

### ISSUE THREAD

**Issue by gapspt** [kibotu/net.kibotu.android.deviceinfo#15]
There seems to be a problem in the getTemperature methods on the Battery.java file.
One method is converting the temperature value to ºC and the other is converting it to ºF, but the temperature itself should already be in one of those formats.
Relevant code:

```
public String getTemperatureCelcius() {
    return convertFahrenheitToCelcius(temperature / 10f) + " °C";
}

public String getTemperatureFarenheit() {
    return convertCelciusToFahrenheit(temperature / 10f) + " °F";
}

// Converts to celcius
private float convertFahrenheitToCelcius(float fahrenheit) {
    return ((fahrenheit - 32) * 5 / 9);
}

// Converts to fahrenheit
private float convertCelciusToFahrenheit(float celsius) {
    return ((celsius * 9) / 5) + 32;
}
```

**Comment by kibotu** [comment]
well a bit late but it's fixed in https://github.com/kibotu/net.kibotu.android.deviceinfo/commit/b154059d3addb0a92a611d34301f49812215ab1a
