### ISSUE TITLE
Failed To resolve   compile 'com.github.kibotu:net.kibotu.android.deviceinfo:-SNAPSHOT'

### ISSUE THREAD

**Issue by faizan321** [kibotu/net.kibotu.android.deviceinfo#18]
Failed To resolve   compile 'com.github.kibotu:net.kibotu.android.deviceinfo:-SNAPSHOT'

**Comment by kibotu** [comment]
does the tag work for you? ```compile 'com.github.kibotu:net.kibotu.android.deviceinfo:1.2.1'```

**Comment by faizan321** [comment]
no same error. with 1.2.1 and 1.2.3

**Comment by faizan321** [comment]
any solution?

**Comment by kibotu** [comment]
not in particular, i'm using the 1.2.1 in at least 4 production projects, also travis and jitpack seem to be able to build those versions 

travis 1.2.1: https://travis-ci.org/kibotu/net.kibotu.android.deviceinfo/builds/154712040
jitpack 1.2.1: https://jitpack.io/#kibotu/net.kibotu.android.deviceinfo/1.2.1
travis 1.2.3: https://travis-ci.org/kibotu/net.kibotu.android.deviceinfo/builds/167726280

perhaps something is different with your environment?

do you try to build with `./gradlew clean build --stacktrace`? (please post the stacktrace)

also if you add it as dependency, do you as well have added jitpack as repository server?

```
allprojects {
		repositories {
			...
			maven { url 'https://jitpack.io' }
		}
	}
```

**Comment by faizan321** [comment]
oh my God i am so much stupid i add the jitpack repository in buildscript{} instead of allprojects{} ...
Now every thing works great.
Thank you so much for help and response.

**Comment by kibotu** [comment]
haha don't worry, made the same mistake at some point, good luck @faizan321 :)
